version: "3.9"

services:
  auctiony-db:
    image: postgres
    restart: always
    container_name: auctiony-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres

volumes:
  postgres:
